### ISSUE TITLE
Plugin keeps defaulting cards on to me (the astro)

### ISSUE THREAD

**Issue by Ants1988** [Nik-Potokar/Astro#2]
Title says it all.

With astro on auto play it keeps giving cards to me regardless of type of card,

**Comment by Nik-Potokar** [comment]
That should only happen if you are the only person in a party.

Or you have the class priority list set on yourself 1st for some reason.

**Comment by Ants1988** [comment]
Its happening in 4 man and 8 man.

**Comment by Nik-Potokar** [comment]
Can you show me your settings?

Also do you have some other auto targeting feature or something like reaction/moaction stacks since that could be in a way of the astro doing its thing?

**Comment by Ants1988** [comment]
I do have moaction on and yeah when im in game later today ill show them.

**Comment by Ants1988** [comment]
https://i.imgur.com/muIZ0iQ.png


Both my MOAction and Astro settings.


I tried it in another roulette 8 man and cards were still going on me regardless of type.

**Comment by Nik-Potokar** [comment]
Very strange since i have just tested it with same settings as you and it deals cards just fine as expected.

Try wiping the addon old and new from its folder and its config file as well.

If that dosent still work tick "deal cards before n seconds before burst" and see if that works

**Comment by Ants1988** [comment]
I'm begging to suspect a plugin conflict with something else installed.

I'm doing a complete dalamud wipe and trying it with just astro, will report back once i've tested

**Comment by Ants1988** [comment]
Alright so -  E1N

I have no plugins installed except Astro - It's working perfectly.

I just need to find whats causing the conflict and avoid it.

**Comment by Nik-Potokar** [comment]
Its probably something that changes the way targeting works/targets stuff for you so my bet is on MOaction.

I use reaction and it works perfectly without issues.

**Comment by Ants1988** [comment]
I'll reinstall moaction next and if it breaks, we got a winner.

**Comment by Ants1988** [comment]
It's not MOAction.

Plugin is still working as intended.

**Comment by Nik-Potokar** [comment]
If you find out what was it please do let me know so if i come across this issue again i can tell people what addon could it be.

Thanks!

**Comment by Ants1988** [comment]
> If you find out what was it please do let me know so if i come across this issue again i can tell people what addon could it be.
> 
> Thanks!

Absolutely. I'm installing them 1 by 1 including the third party ones, once i discover it i'll inform you!

**Comment by Ants1988** [comment]
It was an action stack conflict within MOAction

If I have anything set up for “Play” it conflicts.


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10


________________________________
