### ISSUE TITLE
"official" release?

### ISSUE THREAD

**Issue by jtabox** [Nik-Potokar/Astro#3]
Hey, not exactly an issue, I was mostly wondering if you're considering releasing the plugin through your repo? I know you've been waiting for the author, but I saw now they archived the original repo.

**Comment by Nik-Potokar** [comment]
Yup sadly they haven't replied to me ether or responded to my Issue on their other plugin which seems like it got archived as well.

Here is the link repo link:
`https://raw.githubusercontent.com/Nik-Potokar/Plogons/main/pluginmaster.json`
