### ISSUE TITLE
Updating to 6.4?

### ISSUE THREAD

**Issue by Ants1988** [Nik-Potokar/Astro#6]
Love this plugin, makes playing AST so much easier.

Planning to update to 6.4?

**Comment by Constmar** [comment]
astro is doing something wierd on load, if you turn it on after you start dalamud it's just fine, but if you have it on at boot it causees CTD <.<

**Comment by Nik-Potokar** [comment]
Sorry for the delay i've been super busy irl.

Just testing the update atm so it should be live shortly for 6.4

**Comment by Constmar** [comment]
thank you very much!

**Comment by Nik-Potokar** [comment]
Another update to fix the random plugin not loading issue was pushed so now everything should work as before
