### ISSUE TITLE
Plugin crashes game if loaded at start

### ISSUE THREAD

**Issue by jtabox** [Nik-Potokar/Astro#7]
Since 6.4 (and Dalamud 7.5.2.0) this plugin has consistently caused the game to crash if enabled when entering the game world initially.
So I run XIVLauncher -> main menu -> character select screen -> click my character and as soon as the game shows the loading image it crashes. I've tested it with no other plugins installed, and it's still same issue. No errors are logged in dalamud.log, the game just exits.

Disabling Astro in the plugin loader module that shows in the game's boot main menu gets rid of the error and the game loads normally. Re-enabling Astro once I've logged in works fine and won't crash the game. It's only during the initial loading into the game world.

**Comment by Nik-Potokar** [comment]
Should be updated for 6.4 now and that should fix the crashing issue

**Comment by jtabox** [comment]
Yepp, seems to be working fine after the recent update. Thanks for fixing it :)
Closing this.
