### ISSUE TITLE
Manual Play not working

### ISSUE THREAD

**Issue by BobBongo** [Nik-Potokar/Astro#8]
First of all thanks for keeping this plugin alive,

When ever I use the manual play option it always defaults to casting on me (the astro), I saw the old issue where it was being caused by other plugins (MoAction, I use Reaction though) so I have disabled every plugin (Not uninstalled I dont know if that matters) and it still happens.

What is weird is that auto play will target the correct person and works fine but if I press play manually it always goes on me and I cant think of anything that would be intefering with it.

I have deleted Astro install/config,enabled deal cards in n second, reinstalled, disabled every other plugin and cant get it to work.

Thank you

**Comment by BobBongo** [comment]
Okay

So I reinstalled it manually(Astro.zip) and now Manual Play works in Trials/Raids but not outside of a duty which is fine, (Before it didnt work in trials for me either) 



I dont know if it was the update or I did something wrong before but for now seems good..

Thanks again for the update!!

(It does say AstroReborn (Decomissioned) but hey if it works it works)

**Comment by Nik-Potokar** [comment]
I've just updated the repo so it should be back to normal unless you are running the dev build i sent on discord.

![image](https://github.com/Nik-Potokar/Astro/assets/76532587/6769bc58-3fc4-45ca-b201-762354abef10)

**Comment by BobBongo** [comment]
Yep everything seems to be good now, "Manual Play" setting seems to be working fine in duties.

(If anyone else tries to test this plugin make sure to do it inside a trial or something)

Thanks again for keeping this pluging updated!
